services:
  mongo:
    image: ${user_DH}/my_mongo:latest 
    container_name: mymongoDB
    volumes:
      - "~/mongodb:/data/db"
    networks:
      - network1
    restart: always

  webserver:
    image: ${user_DH}/my_nodejs_app:latest  
    container_name: nginx
    ports:
      - "3000:3000"
    networks:
      - network1
    restart: always

networks:
  network1:
